# Generated by Django 2.2.1 on 2019-05-21 01:25

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(help_text='Enter full name documentation', max_length=255)),
                ('Email', models.CharField(help_text='Enter email documentation', max_length=255)),
                ('Message', models.TextField(help_text='Enter message')),
            ],
            options={
                'ordering': ['Name', 'Email', 'Message'],
            },
        ),
    ]
